In [1]:
#Question 1
#If you’re given two lists:
#A = [1,2,3,4,5,6], B = [13, 21, 34]
#The task is to create a list with the elements of A and B in a single dimension with output:
#A_B = [1,2,3,4,5,6,13, 21, 34]
#Which of the following option is the best way to create this list?

#Answer
A = [1,2,3,4,5,6]
B = [13,21,34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [2]:
#Question 2
#How do you create an identity matrix in python?

#Answer
import numpy as np

ident_matrix = np.identity(3)
print(ident_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#Question 3
#Which of the following fuel type code has the lowest average fuel cost per unit burned?

#Answer
import pandas as pd

#import the data from github repo
url = 'https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw=true'
fuel_data = pd.read_csv(url, error_bad_lines = False)

#describe the data
#print(fuel_data.describe(include='all'))

#check for missing values
print(fuel_data.isnull().sum())


#use groupby to count the sum of each unique value in the fuel unit column
fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].count()

#calculate the mean for each fuel_type_code_pudl
mean_fuel_type_fuel_cost = fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean()

#print the mean 
print(mean_fuel_type_fuel_cost)

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64


In [ ]:
#Gas

In [5]:
#Question 4
#What is the standard deviation and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places?

#Answer
# describe  Fuel_mmbtu_per_unit to get the 75th the standard deviation and
# 75th percentile 
print(fuel_data["fuel_mmbtu_per_unit"].describe())

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64


In [6]:
#Standard Deviation for Fuel_mmbtu_per_unit is 10.60 to 2 decimal place
#75th percentile for Fuel_mmbtu_per_unit is 17.01 to 2 decimal place

In [7]:
#Question 5
#What is the skewness and kurtosis for the fuel quantity burned in two decimal places?

#calculate  skewness for  fuel_qty_burned
skew_for_the_fuel_qty_burned = fuel_data["fuel_qty_burned"].skew()

# print skewness for  fuel_qty_burned in 2 decimal places
print('Skewness: %.2f' % (skew_for_the_fuel_qty_burned))

#calculate  kurtosis for  fuel_qty_burned
kurt_for_the_fuel_qty_burned = fuel_data["fuel_qty_burned"].kurt()

# print kurtosis for  fuel_qty_burned in 2 decimal places
print('Kurtosis: %.2f' % (kurt_for_the_fuel_qty_burned))

Skewness: 15.85
Kurtosis: 651.37


In [8]:
#Question 6
#Which feature has missing values and what is the total number of missing value #and percentage of the missing rows as a factor of the total number of rows in #three decimal places?
#(Enter answer in the format: Feature: xxx, Total: xxx, Percent: xxx)

#Answer
#check for missing values
print(fuel_data.isnull().sum())

num_of_missing_rows = 180
total_rows = 29523

#calculate percentage of missing rows
perc_of_missing_rows = (num_of_missing_rows/29523)*100
#print percentage of missing rows
print('Percent:', perc_of_missing_rows)

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
Percent: 0.609694136774718


In [9]:
#percentage of missing rows is 0.610 

In [10]:
#Question 7
#The feature with missing values falls under what category? What missing value imputation technique would you use?

#Answer 
#Categorical and mode imputation

In [11]:
#Question 8
#Which of the features has the second and third lowest correlation with the Fuel Cost Per Unit Burned?

#Answer
#find the correlation and print
print(fuel_data.corr().sum())

utility_id_ferc1                0.920774
report_year                     1.005239
fuel_qty_burned                 0.850576
fuel_mmbtu_per_unit             0.716298
fuel_cost_per_unit_burned       0.957737
fuel_cost_per_unit_delivered    0.967851
fuel_cost_per_mmbtu             1.008057
dtype: float64


In [12]:
#Feature with second correlation with Fuel Cost Per Unit Burned is fuel_qty_burned (0.850576)
#Feature with second correlation with Fuel Cost Per Unit Burned is fuel_mmbtu_per_unit (0.716298)

In [14]:
#Question 9
#For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?

#find the yearly report of fuel_type_code_pudl 
fuel_data.groupby(['fuel_type_code_pudl','report_year'])['fuel_cost_per_unit_burned'].sum()

fuel_type_code_pudl  report_year
coal                 1994           14984.572
                     1995           14571.785
                     1996           12694.803
                     1997           43742.178
                     1998           11902.597
                                      ...    
waste                2014             591.594
                     2015             629.270
                     2016             539.079
                     2017             452.079
                     2018             660.972
Name: fuel_cost_per_unit_burned, Length: 148, dtype: float64

In [15]:
fuel_cost_per_unit_burned_in_1994 = 14984.572
fuel_cost_per_unit_burned_in_1998 = 11902.597

#Percentage change 
percentage_change = ((fuel_cost_per_unit_burned_in_1994 - fuel_cost_per_unit_burned_in_1998)/fuel_cost_per_unit_burned_in_1994)*100
#print percentage change
print('Percentage change between 1994 and 1998:%.0f' % percentage_change+'%')

Percentage change between 1994 and 1998:21%


In [16]:
#Question 10
#Which year has the highest average fuel cost per unit delivered?

#calculate the mean for each fuel_type_code_pudl
fuel_cost_per_unit_delivered = fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].mean()

#print mean of fuel_cost_per_unit_delivered per year 
print(fuel_cost_per_unit_delivered)

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64


In [ ]:
#Answer: 1997